id: AEE38591A
title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling to the
  Realm of Lotus Light'
type: translation
pechas:
- I5553F996
- I25923A9C
- IBE65487F
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:30:57.595139
  last_modified_at: 2023-01-04 12:30:57.595143
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I5553F996/84A8: 835B
  I25923A9C/D66A: 835B
  IBE65487F/DBCB: 835B
